### ISSUE TITLE
Deployment CI is broken

### ISSUE THREAD

**Issue by josephineweidner** [sanctuarycomputer/food#1]
### The problem

Twist context: https://twist.com/a/133876/ch/467805/t/5911103/

Upon merging to `master` and triggering the CircleCI deployment job, we encounter this error: 
```
Writing SSH key for checkout to "/home/circleci/.ssh/id_rsa"
Writing SSH public key for checkout to "/home/circleci/.ssh/id_rsa.pub"
Cloning git repository
Cloning into '.'...
Warning: Permanently added the ECDSA host key for IP address '140.82.113.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
```

I think the SSH key on this project expired because there are none in the repo. I also think I need access to the CircleCI project in order to add it there (https://circleci.com/docs/getting-started/) but can't find the creds in 1Password. 

### Hacky workaround

You can upload a new `index.html` with the changes needed directly to `s3` where it's hosted. 1Password > garden3d > Shared > AWS. Then navigate to the "food.sanctuary.computer" bucket and upload a new `index.html` file.

**Comment by hhff** [comment]
@josephineweidner let's just move to vercel

**Comment by josephineweidner** [comment]
Moved to vercel, changes are reflected in readme
